services:
  raindrop-poster:
    container_name: raindrop-poster
    image: raindrop-poster:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - raindrop-data:/app/data
    restart: unless-stopped

volumes:
  raindrop-data:
    driver: local
